### ISSUE TITLE
Wizard not allowing Project Manager to Complete Milestone

### ISSUE THREAD

**Issue by CEOehis** [Chingu-cohorts/voyage-wiki#17] opened 2018-02-18 14:26 UTC
When trying to complete first milestone - `milestone 0` - I get 'You are not the project manager of this team'. I was advised to submit a stand up so I can view `team standups` and thereby see the list of team members and confirm who the project manager is supposed to be, which I did but that button just loads for a few seconds and stops
![Team-workspace](https://user-images.githubusercontent.com/25967737/36352927-ee4d73a6-14bf-11e8-868e-aacb3584ff3a.png)

**Comment by jdmedlock** [comment] 2018-02-18 14:54
Assigned to Wizard Team. This is a duplicate of [Issue #13](https://github.com/Chingu-cohorts/voyage-wiki/issues/13)

**Comment by the-vampiire** [comment] 2018-02-19 08:28
@jdmedlock fixed. he was not set as PM in the team in the database (but is the PM in the spreadsheet).

all wizard bugs related to team standups not loading or milestones not submitting are due to the team not having a PM set in the database. issue #13 doesnt have a PM set in the spreadsheet - cant fix.

**Closed** 2018-02-19 13:48 UTC
Labels: priority:must have, scope:story, state:done, status:duplicate, type:bug
